### ISSUE TITLE
Test Failure?

### ISSUE THREAD

**Issue by martindevans** [genaray/Arch.Extended#35]
At the moment the `JsonWorldSerialization` test seems to fail with this error:

 - System.InvalidOperationException : Register must call on startup(before use GetFormatter<T>).

I haven't investigated this much, but it looks like it's coming from inside `Utf8Json`.

Is this something I'm doing wrong, or is this feature broken at the moment?

**Comment by genaray** [comment]
Interesting, I'll have a look at it later. What is the call stack? ^^

**Comment by martindevans** [comment]
```System.InvalidOperationException : Register must call on startup(before use GetFormatter<T>).
   at Utf8Json.Resolvers.CompositeResolver.Register(IJsonFormatter[] formatters)
   at Utf8Json.Resolvers.CompositeResolver.RegisterAndSetAsDefault(IJsonFormatter[] formatters, IJsonFormatterResolver[] resolvers)
   at Arch.Persistence.ArchJsonSerializer..ctor(IJsonFormatter[] custFormatters) in C:\Users\Martin\Documents\dotnet\Arch.Extended\Arch.Persistence\Serializer.cs:line 278
   at Arch.Persistence.Tests.Tests.Setup() in C:\Users\Martin\Documents\dotnet\Arch.Extended\Arch.Persistence.Tests\PersistenceTest.cs:line 39
   at InvokeStub_Tests.Setup(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)```

**Comment by genaray** [comment]
Should now be fixed ^^
